version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.11
    commands:
      - echo "Installing AWS SAM CLI"
      - pip install aws-sam-cli

  build:
    commands:
      - echo "Building SAM application"
      - sam build

  post_build:
    commands:
      - echo "Packaging SAM template"
      - sam package \
          --template-file template.yaml \
          --s3-bucket vib-sam-artifacts-bucket \
          --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml